# local data loaders
height: 224
width: 224
seq_len: 16
train_bz: 4
test_bz: 8
num_workers: 4

# network architecture
arch: 'i3d_r50'
num_classes: 83
pretrained_model: 'https://download.openmmlab.com/mmaction/recognition/i3d/i3d_r50_32x2x1_100e_kinetics400_rgb/i3d_r50_32x2x1_100e_kinetics400_rgb_20200614-c25ef9a4.pth'

# training
epochs: 100
loss: 'CrossEntropyLoss'
optimizer: 'SGD'
lr: 0.00025
clip_gradient: 20
print_freq: 20