# local data loaders
height: 224
width: 224
seq_len: 16
train_bz: 4
test_bz: 8
num_workers: 4

# network architecture
arch: 'slowfast_r50'
num_classes: 83
pretrained_model: 'https://download.openmmlab.com/mmaction/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb/slowfast_r50_8x8x1_256e_kinetics400_rgb_20200716-73547d2b.pth'

# training
epochs: 100
loss: 'CrossEntropyLoss'
optimizer: 'SGD'
lr: 0.00025
clip_gradient: 20
print_freq: 20