# local data loaders
height: 224
width: 224
seq_len: 16
train_bz: 4
test_bz: 8
num_workers: 4

# network architecture
arch: 'r2plus1d_r34'
num_classes: 83
pretrained_model: 'https://download.openmmlab.com/mmaction/recognition/r2plus1d/r2plus1d_r34_256p_8x8x1_180e_kinetics400_rgb/r2plus1d_r34_256p_8x8x1_180e_kinetics400_rgb_20200729-aa94765e.pth'

# training
epochs: 100
loss: 'CrossEntropyLoss'
optimizer: 'SGD'
lr: 0.00025
clip_gradient: 20
print_freq: 20